/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rk8359041 (https://sketchfab.com/rk8359041)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bouncing-soccer-ball2-c08cfdbaf515464a8c1cc05b3ce8934d
title: Bouncing soccer ball2
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function ModelP({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./assets/pelota/scene.gltf')
  const { actions } = useAnimations(animations, group)
  let nome = "soccer_ball_bounce";
  useEffect(()=>{
    actions[nome].play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal3_3" scale={0.33}>
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="soccer_ball2_2_correction" scale={3.03}>
                      <group name="soccer_ball2_2" />
                    </group>
                    <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry}  castShadow material={materials.material_0} skeleton={nodes.Object_19.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./assets/pelota/scene.gltf')
